### ISSUE TITLE
gulp install command

### ISSUE THREAD

**Issue by crazedVic** [JayeshLab/bootstrap-4-sass-gulp-4-boilerplate#1]
Followed your instructions on my mac.  Could not get gulp to run, got error below.  
Did some checking, and apparently i had to install gulp using **npm install -g gulp-cli**, which worked.

MacBook-Pro:bootstrap4 user$ gulp dev
[10:24:32] Using gulpfile ~/Projects/BootstrapCSS/bootstrap4/gulpfile.js
/Users/user/.npm-global/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                   ^
TypeError: Cannot read property 'apply' of undefined
    at /Users/user/.npm-global/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (internal/process/next_tick.js:61:11)

**Comment by wrabit** [comment]
Same here - check your gulp versions. `gulp -v` This repo require gulp 4. If you have different installed globally (like me) then run the local version: `$ node_modules/gulp/bin/gulp.js`

**Comment by JayeshLab** [comment]
Thanks for using it, This boilerplate uses Gulp 4, If you do not have it at global, install locally as @williamabbott commented.
