### ISSUE TITLE
how can I import other html files, other layers or components into an html file?

### ISSUE THREAD

**Issue by Alexander171176** [JayeshLab/bootstrap-4-sass-gulp-4-boilerplate#10]
Hello sir! 

How to split html into layers or components, for example, connect header or footer from another html file? Which lines of code should be added to gulpfile.js and how to import other html files located in the created components folder into an html file? I need to connect a lot of individual html files. Task: Splitting one html file into several. Please write how this can be done, if it is not difficult for you to explain. Thank you in advance!

**Comment by JayeshLab** [comment]
There is a gulp library [https://github.com/zaharin/gulp-html-tag-include](https://github.com/zaharin/gulp-html-tag-include) which can let you include other html into your main html, like adding common header and footer into your html just like template. You can find tutorial of how to do that [https://dev.to/caiojhonny/html-includes-with-gulp-js-2def](https://dev.to/caiojhonny/html-includes-with-gulp-js-2def). Let me know if that solves your problem.
