### ISSUE TITLE
Watching sass files in sub-folders

### ISSUE THREAD

**Issue by arleym** [JayeshLab/bootstrap-4-sass-gulp-4-boilerplate#2]
If one organizes their Sass into subfolders, one must also update the gulpfile from `gulp.watch('src/sass/*.scss'` to `gulp.watch('src/sass/**/*.scss'` - I find though that this tiny change makes gulp recursively refresh every time the output CSS updates?! Not sure why that happens! haha

**Comment by JayeshLab** [comment]
Thanks for your comment. If subfolders needs to be included, then watch statement should be `gulp.watch(['assets/scss/*.scss','assets/scss/**/*.scss','!assets/scss/bootstrap/**'],` excluding bootstrap subfolder as it get copied from node_module, which makes recursive refresh. I have committed the change in gulp file to include subfolders in scss watch.

**Comment by arleym** [comment]
Perfect! Thank you so much. I love how little this boilerplate does, and that it's done in such a clear way. I really loathe working on this kind of tooling stuff and was disappointed that a move to Gulp 4 made my little cardhouse repo break, heh. 

Thanks for the quick reply! Time saver :)
