### ISSUE TITLE
import selective JavaScript from Bootstrap

### ISSUE THREAD

**Issue by Allmedialab** [JayeshLab/bootstrap-4-sass-gulp-4-boilerplate#5]
Hi,

Thanks for the wonderful boilerplate! Would it be possible to import selective Bootstrap JavaScript that go's to the dist/js/vendor/bootstrap.bundle.min.js and how can that be done in this setup?

Regards,
David

**Comment by JayeshLab** [comment]
Bootstrap.bundle.min.js  includes popper.js and bootstrap.js. Bootstrap.js is compiled and minified  from individual plugin js files. You can copy those from ./node_modules/bootstrap/js/dist and use them individually. But you have to take care of their dependencies.
