### ISSUE TITLE
Minified versions of CSS and JS files are not called in the dist/index.html

### ISSUE THREAD

**Issue by Ajax30** [JayeshLab/bootstrap-4-sass-gulp-4-boilerplate#7]
Thos chunk of code does not do the hob it is supposed to (**replace** HTML block for Js and Css file upon build):

```
// Replace HTML block for Js and Css file upon build and copy to /dist
gulp.task('replaceHtmlBlock', function () {
  return gulp.src(['*.html'])
    .pipe(htmlreplace({
      'js': 'assets/js/app.min.js',
      'css': 'assets/css/app.min.css'
    }))
    .pipe(gulp.dest('dist/'));
});
```

**Comment by JayeshLab** [comment]
There are two gulp task.
i) **gulp dev** - Starts a local server with browserSync and hot reloading on changes to files (HTML, SCSS, JS).
ii) **gulp** - To compile scss to css, minify css and js and build ready for production files in dist folder.

The second task does the replacement with minified css and js in index.html.
