### ISSUE TITLE
Dist Html file asset path is not updates

### ISSUE THREAD

**Issue by pravinweb** [JayeshLab/bootstrap-4-sass-gulp-4-boilerplate#9]
Thanks for quick boilerplate, 

When we run gulp build task index html get copied into dist folder but it shows 404 error for js file as in dist asset folder js file have min extension but same is not getting updated in index html

**Comment by JayeshLab** [comment]
**gulp build**  will only copy the assets into dist folder. You need to run only **gulp** command. It will run gulp task **clean, build and replaceHtml** (In index.html it will replace assets with minified one)
